# Generated by Django 2.2.3 on 2019-07-19 23:20

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wcoa', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='masonrypage',
            name='author',
        ),
        migrations.RemoveField(
            model_name='masonrypage',
            name='date',
        ),
        migrations.AlterField(
            model_name='masonrypage',
            name='body',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock(classname='block-title')), ('text', wagtail.core.blocks.RichTextBlock()), ('brick', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock()), ('text', wagtail.core.blocks.RichTextBlock()), ('photo', wagtail.images.blocks.ImageChooserBlock(required=False))])), ('image', wagtail.images.blocks.ImageChooserBlock())]),
        ),
    ]
