# Generated by Django 2.2.3 on 2019-07-25 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wcoa', '0002_auto_20190724_0025'),
        ('wcoa', '0003_auto_20190720_0001'),
    ]

    operations = [
    ]
