# Generated by Django 2.2.3 on 2019-07-25 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wcoa', '0005_remove_connectpage_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectpage',
            name='body_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='base.PortalImage'),
        ),
    ]
