# Generated by Django 2.2.3 on 2019-07-25 23:08

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('wcoa', '0006_auto_20190725_2248'),
    ]

    operations = [
        migrations.CreateModel(
            name='CTAPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('body', wagtail.fields.StreamField([('item', wagtail.blocks.StructBlock([('cta_title', wagtail.blocks.CharBlock()), ('cta_content', wagtail.blocks.RichTextBlock()), ('cta_link', wagtail.blocks.URLBlock(label='URL', required=False)), ('width', wagtail.blocks.IntegerBlock(help_text='Number of columns to span out of 12 (e.g., input of 3 would mean give this a width of 3 out of the 12 (25%))', max_value=12, min_value=0, required=False))])), ('details', wagtail.blocks.RichTextBlock())])),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AlterField(
            model_name='connectpage',
            name='cta_list',
            field=wagtail.fields.StreamField([('connection', wagtail.blocks.StructBlock([('cta_title', wagtail.blocks.CharBlock()), ('cta_content', wagtail.blocks.RichTextBlock()), ('cta_link', wagtail.blocks.URLBlock(label='URL', required=False)), ('width', wagtail.blocks.IntegerBlock(help_text='Number of columns to span out of 12 (e.g., input of 3 would mean give this a width of 3 out of the 12 (25%))', max_value=12, min_value=0, required=False))])), ('details', wagtail.blocks.RichTextBlock())]),
        ),
        migrations.AlterField(
            model_name='masonrypage',
            name='body',
            field=wagtail.fields.StreamField([('heading', wagtail.blocks.CharBlock(classname='block-title')), ('text', wagtail.blocks.RichTextBlock()), ('brick', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock()), ('text', wagtail.blocks.RichTextBlock()), ('page', wagtail.blocks.PageChooserBlock(label='page', required=False)), ('external_url', wagtail.blocks.URLBlock(label='external URL', required=False)), ('photo', wagtail.images.blocks.ImageChooserBlock(required=False))])), ('image', wagtail.images.blocks.ImageChooserBlock(required=False))]),
        ),
    ]
