# Generated by Django 2.2.3 on 2019-07-26 22:00

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wcoa', '0009_auto_20190725_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectpage',
            name='cta_list',
            field=wagtail.fields.StreamField([('connection', wagtail.blocks.StructBlock([('cta_title', wagtail.blocks.CharBlock(required=False)), ('cta_content', wagtail.blocks.RichTextBlock(required=False)), ('cta_link', wagtail.blocks.URLBlock(label='URL', required=False)), ('width', wagtail.blocks.IntegerBlock(help_text='Number of columns to span out of 12 (e.g., input of 3 would mean give this a width of 3 out of the 12 (25%))', max_value=12, min_value=0, required=False)), ('background_color', wagtail.blocks.ChoiceBlock(choices=[('blue', 'Blue'), ('green', 'Green')], icon='color', required=False)), ('background_image', wagtail.images.blocks.ImageChooserBlock(required=False))])), ('details', wagtail.blocks.RichTextBlock())]),
        ),
        migrations.AlterField(
            model_name='ctapage',
            name='body',
            field=wagtail.fields.StreamField([('item', wagtail.blocks.StructBlock([('cta_title', wagtail.blocks.CharBlock(required=False)), ('cta_content', wagtail.blocks.RichTextBlock(required=False)), ('cta_link', wagtail.blocks.URLBlock(label='URL', required=False)), ('width', wagtail.blocks.IntegerBlock(help_text='Number of columns to span out of 12 (e.g., input of 3 would mean give this a width of 3 out of the 12 (25%))', max_value=12, min_value=0, required=False)), ('background_color', wagtail.blocks.ChoiceBlock(choices=[('blue', 'Blue'), ('green', 'Green')], icon='color', required=False)), ('background_image', wagtail.images.blocks.ImageChooserBlock(required=False))])), ('details', wagtail.blocks.RichTextBlock())]),
        ),
        migrations.AlterField(
            model_name='masonrypage',
            name='body',
            field=wagtail.fields.StreamField([('heading', wagtail.blocks.CharBlock(classname='block-title', required=False)), ('text', wagtail.blocks.RichTextBlock(required=False)), ('brick', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(required=False)), ('text', wagtail.blocks.RichTextBlock(required=False)), ('page', wagtail.blocks.PageChooserBlock(label='page', required=False)), ('external_url', wagtail.blocks.URLBlock(label='external URL', required=False)), ('photo', wagtail.images.blocks.ImageChooserBlock(required=False))])), ('image', wagtail.images.blocks.ImageChooserBlock(required=False))]),
        ),
    ]
