# Generated by Django 2.2.3 on 2019-08-02 20:12

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wcoa', '0011_auto_20190801_0240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectpage',
            name='cta_list',
            field=wagtail.core.fields.StreamField([('connection', wagtail.core.blocks.StructBlock([('cta_title', wagtail.core.blocks.CharBlock(required=False)), ('cta_content', wagtail.core.blocks.RichTextBlock(required=False)), ('cta_link', wagtail.core.blocks.URLBlock(label='URL', required=False)), ('width', wagtail.core.blocks.IntegerBlock(help_text='Number of columns to span out of 12 (e.g., input of 3 would mean give this a width of 3 out of the 12 (25%))', max_value=12, min_value=0, required=False)), ('text_color', wagtail.core.blocks.ChoiceBlock(choices=[('white', 'White'), ('black', 'Black'), ('blue', 'Blue'), ('green', 'Green'), ('red', 'Red'), ('purple', 'Purple'), ('grey', 'Grey')], icon='color_palette', required=False)), ('background_color', wagtail.core.blocks.ChoiceBlock(choices=[('white', 'White'), ('black', 'Black'), ('blue', 'Blue'), ('green', 'Green'), ('red', 'Red'), ('purple', 'Purple'), ('grey', 'Grey')], icon='color', required=False)), ('background_image', wagtail.images.blocks.ImageChooserBlock(required=False))])), ('details', wagtail.core.blocks.RichTextBlock())]),
        ),
        migrations.AlterField(
            model_name='ctapage',
            name='body',
            field=wagtail.core.fields.StreamField([('item', wagtail.core.blocks.StructBlock([('cta_title', wagtail.core.blocks.CharBlock(required=False)), ('cta_content', wagtail.core.blocks.RichTextBlock(required=False)), ('cta_link', wagtail.core.blocks.URLBlock(label='URL', required=False)), ('width', wagtail.core.blocks.IntegerBlock(help_text='Number of columns to span out of 12 (e.g., input of 3 would mean give this a width of 3 out of the 12 (25%))', max_value=12, min_value=0, required=False)), ('text_color', wagtail.core.blocks.ChoiceBlock(choices=[('white', 'White'), ('black', 'Black'), ('blue', 'Blue'), ('green', 'Green'), ('red', 'Red'), ('purple', 'Purple'), ('grey', 'Grey')], icon='color_palette', required=False)), ('background_color', wagtail.core.blocks.ChoiceBlock(choices=[('white', 'White'), ('black', 'Black'), ('blue', 'Blue'), ('green', 'Green'), ('red', 'Red'), ('purple', 'Purple'), ('grey', 'Grey')], icon='color', required=False)), ('background_image', wagtail.images.blocks.ImageChooserBlock(required=False))])), ('details', wagtail.core.blocks.RichTextBlock())]),
        ),
    ]
