# Generated by Django 2.2.3 on 2019-09-10 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wcoa', '0014_auto_20190816_2348'),
        ('wcoa', '0013_auto_20190808_1803'),
    ]

    operations = [
    ]
