# Generated by Django 2.2.7 on 2019-11-22 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('wcoa', '0017_catalogiframepage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MasonryPage',
        ),
    ]
