# Generated by Django 2.2.9 on 2020-09-22 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wcoa', '0018_delete_masonrypage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogiframepage',
            name='source',
            field=models.URLField(max_length=1999),
        ),
    ]
