# Generated by Django 4.2 on 2024-02-28 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0083_workflowcontenttype'),
        ('wcoa', '0021_auto_20240226_2231'),
    ]

    operations = [
        migrations.CreateModel(
            name='OHIClass',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.RenameModel(
            old_name='IndicatorCategory',
            new_name='OHICategory',
        ),
        migrations.RenameModel(
            old_name='IndicatorPage',
            new_name='OHIIndicatorPage',
        ),
    ]
