# Generated by Django 4.2 on 2024-02-28 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_portalrendition_file'),
        ('wcoa', '0022_ohiclass_rename_indicatorcategory_ohicategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ohiclass',
            name='ohiclass_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='base.portalimage'),
        ),
    ]
