# Generated by Django 4.2 on 2024-02-29 00:13

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wcoa', '0024_ohicategory_ohicategory_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ohiindicatorpage',
            name='body',
            field=wagtail.fields.StreamField([('Score', wagtail.blocks.StructBlock([('state', wagtail.blocks.ChoiceBlock(choices=[('West Coast', 'West Coast'), ('CA', 'California'), ('OR', 'Oregon'), ('WA', 'Washington')])), ('image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('year', wagtail.blocks.IntegerBlock(help_text='Year of the report', required=False)), ('report', wagtail.blocks.URLBlock(help_text='URL to the report', required=False))])), ('WYSIWYG', wagtail.blocks.StructBlock([('width', wagtail.blocks.ChoiceBlock(choices=[('1', '1/12'), ('2', '2/12'), ('3', '3/12'), ('4', '4/12'), ('5', '5/12'), ('6', '6/12'), ('7', '7/12'), ('8', '8/12'), ('9', '9/12'), ('10', '10/12'), ('11', '11/12'), ('12', '12/12')], icon='arrow-right', required=False)), ('content', wagtail.blocks.RichTextBlock(required=False)), ('text_color', wagtail.blocks.ChoiceBlock(choices=[('white', 'White'), ('black', 'Black'), ('blue', 'Blue'), ('green', 'Green'), ('red', 'Red'), ('purple', 'Purple'), ('grey', 'Grey')], icon='color_palette', required=False)), ('background_color', wagtail.blocks.ChoiceBlock(choices=[('white', 'White'), ('black', 'Black'), ('blue', 'Blue'), ('green', 'Green'), ('red', 'Red'), ('purple', 'Purple'), ('grey', 'Grey')], icon='color', required=False)), ('background_image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('border_color', wagtail.blocks.ChoiceBlock(choices=[('white', 'White'), ('black', 'Black'), ('blue', 'Blue'), ('green', 'Green'), ('red', 'Red'), ('purple', 'Purple'), ('grey', 'Grey')], icon='color_palette', required=False)), ('border_width', wagtail.blocks.IntegerBlock(help_text='Width of the border in pixels', required=False))]))], use_json_field=True),
        ),
    ]
