# Generated by Django 4.2 on 2024-03-06 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_portalrendition_file'),
        ('wcoa', '0027_alter_ohiindicatorpage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='ohiindicatorpage',
            name='indicator_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='base.portalimage'),
        ),
    ]
