# Generated by Django 4.2 on 2024-03-12 23:30

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wcoa', '0029_ohidashboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='ohidashboard',
            name='body',
            field=wagtail.fields.StreamField([('content', wagtail.blocks.RichTextBlock(required=False))], default='{"blocks":[{"key":"j9bes","text":"one","type":"ordered-list-item","depth":0,"inlineStyleRanges":[],"entityRanges":[],"data":{}},{"key":"e9r3j","text":"","type":"ordered-list-item","depth":0,"inlineStyleRanges":[],"entityRanges":[],"data":{}}],"entityMap":{}}', use_json_field=True),
            preserve_default=False,
        ),
    ]
