# Generated by Django 4.2 on 2024-03-16 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wcoa', '0030_ohidashboard_body'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ohicategory',
            old_name='ohicategory_image',
            new_name='img',
        ),
        migrations.RenameField(
            model_name='ohiclass',
            old_name='ohiclass_image',
            new_name='img',
        ),
        migrations.RenameField(
            model_name='ohiindicatorpage',
            old_name='indicator_image',
            new_name='img',
        ),
    ]
