# Generated by Django 4.2 on 2024-03-21 18:48

from django.db import migrations, models
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wcoa', '0031_rename_ohicategory_image_ohicategory_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ohidashboard',
            name='description',
            field=wagtail.fields.RichTextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='ohidashboard',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
