# Generated by Django 4.2 on 2024-03-21 18:57

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wcoa', '0032_alter_ohidashboard_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ohicategory',
            name='name',
        ),
        migrations.RemoveField(
            model_name='ohiclass',
            name='name',
        ),
        migrations.RemoveField(
            model_name='ohidashboard',
            name='description',
        ),
        migrations.RemoveField(
            model_name='ohidashboard',
            name='name',
        ),
        migrations.RemoveField(
            model_name='ohiindicatorpage',
            name='description',
        ),
        migrations.RemoveField(
            model_name='ohiindicatorpage',
            name='name',
        ),
        migrations.AlterField(
            model_name='ohidashboard',
            name='body',
            field=wagtail.fields.StreamField([('content', wagtail.blocks.RichTextBlock(required=False))], blank=True, use_json_field=True),
        ),
    ]
